### ISSUE TITLE
Interface von App Design erstellen:

### ISSUE THREAD

**Issue by janewhat** [th-koeln/location-based-messages#52]
- Layout für Nachrichten löschen
- Layout für Nachrichten bearbeiten
- Layout für Nachrichten erstellen
- Layout für Nachrichten lesen
- Layout User-Registrierung

**Comment by janewhat** [comment]
[layouts-v1.pdf](https://github.com/th-koeln/location-based-messages/files/2235616/layouts-v1.pdf)

**Comment by janewhat** [comment]
![layouts-v1](https://user-images.githubusercontent.com/5556200/43319144-ef46f1a4-91a3-11e8-8aa9-17e9af7465ba.png)

**Comment by aleksandrashekh** [comment]
![wireframes](https://user-images.githubusercontent.com/34030679/43371279-c0d64f8a-938e-11e8-9c8b-ece987d9c01f.png)

So ungefähr soll unseres App ablaufen.
Bitte um Anmerkungen und Vorschläge.

Folgende Fragen sollen noch geklärt sein:
- Was ist genau wenn User "anonym" ist ? Ich habe es so verstanden, dass er sich nicht registrieren soll. Oder soll es so sein, dass man es in Einstellungen ändern kann?
- Was soll beim User Profile angezeigt sein? 
    - Wenn man vor Ort/nicht vor Ort ist. 
    - Wenn man als Anonym dadrin ist. 
    - Erstellte Nachrichten?

- Nachrichten können nur vor Ort bearbeitet und gelöscht sein? Ist es sinnvoll von UX Sicht?
- User Profile icon
- "Aktualisieren" Button sofort anzeigen? Ist es nicht verwirrend?

**Comment by aleksandrashekh** [comment]
<img width="601" alt="prototyp" src="https://user-images.githubusercontent.com/34030679/43371350-23fb7382-9390-11e8-8cb1-d059b2085525.png">

Erste Version.
Wird noch geändert und verbessert bis zum Treffen am Donnerstag.

**Comment by aleksandrashekh** [comment]
- Standtort richtig zeigen.
- Screen für Username erstellen.
- Name von Ersteller beim Nachricht zeigen.
- "Aktualisieren" Button weg machen. ( zu Swipefunktion ändern? Eventuell gucken was sinnvoll ist.)
- Beim User Profile wenn man nicht vor Ort näherstes Beacon anzeigen.
- User Profile - lesen, schreiben usw.
- Text-/Audio-/Videonachrichten Möglichkeit realisieren.
- Farben vllt. änderen. Andere Optionen.

**Comment by aleksandrashekh** [comment]
**Gesamte View:**
<img width="617" alt="screen shot 2018-08-02 at 18 44 20" src="https://user-images.githubusercontent.com/34030679/43598193-6b434aa2-9684-11e8-8e54-8afa9c5fde4e.png">

**Grosser:**

<img width="821" alt="screen shot 2018-08-02 at 18 46 57" src="https://user-images.githubusercontent.com/34030679/43598290-a4542690-9684-11e8-86ad-23c612d96de6.png">

<img width="906" alt="screen shot 2018-08-02 at 18 47 11" src="https://user-images.githubusercontent.com/34030679/43598309-b3097ae6-9684-11e8-9ba6-8a025b042c36.png">

<img width="397" alt="screen shot 2018-08-02 at 18 47 30" src="https://user-images.githubusercontent.com/34030679/43598335-bb83ba74-9684-11e8-8fe6-9d82477f4228.png">


Das ist die 2. Version.

Zu klären:
- Text-/Audio-/Videonachrichten Möglichkeit realisieren ??
- Farben Auswahl. 
- Nachricht erstellen.

**Comment by aleksandrashekh** [comment]
Besprechung von 02.08.2018.

Was noch zu tun bei UI:

- Typ von Nachrichten auswählen. ( welche gibt es?)

**Comment by bsari** [comment]
Screens wurden erstellt, nur noch controller anpassen!

**Comment by aleksandrashekh** [comment]
<img width="607" alt="screens" src="https://user-images.githubusercontent.com/34030679/44001653-2ac7c804-9e36-11e8-8068-0448110f94db.png">

**Comment by aleksandrashekh** [comment]
Logos für App und für Augmented Reality Erkennung

[LOGO LBM.zip](https://github.com/th-koeln/location-based-messages/files/2405431/LOGO.LBM.zip)
